# basic system
sys-kernel/gentoo-kernel-bin
sys-kernel/installkernel
sys-kernel/linux-firmware

# dots tools
app-admin/doas
app-admin/eclean-kernel
dev-vcs/git

# system setup
app-admin/sysklogd
net-firewall/nftables
net-misc/openssh
sys-firmware/intel-microcode
sys-process/fcron

# system tools
app-containers/podman-compose

# not needed
sys-process/btop
sys-process/htop
