version: "3"
networks:
  private:
  public:
services:
  haproxy:
    container_name: haproxy
    image: docker.io/haproxy:alpine
    sysctls: ["net.ipv4.ip_unprivileged_port_start=0"]
    networks: ["public", "private"]
    ports: ["80:80", "443:443"]
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /mnt/data/managed/acme/certs:/certs

  teste1:
    container_name: teste1
    image: docker.io/traefik/whoami:latest
    environment:
      - WHOAMI_NAME=gs_home_teste1
    networks: ["public"]
    expose: ["80"]

  teste2:
    container_name: teste2
    image: docker.io/traefik/whoami:latest
    environment:
      - WHOAMI_NAME=gs_home_teste2
    networks: ["private"]
    expose: ["80"]
