# http://fcron.free.fr/doc/en/fcrontab.5.html

# runs once a day
# %daily,random,serial * 2-8 \
#   duncache --pusage 80 --source /mnt/storage/fast --target /mnt/storage/slow && \
#   dsnap --max-deleted 5 --max-updated 10

# runs once on startup
# @runatreboot,runonce,serial 1 \
#   snapraid fix && \
#   set-mounts-permissions
@runas(podman),runatreboot,runonce 1 \
  until podman-compose -f /etc/podman/compose.yaml up -d; do sleep 10; done

# @runas(podman),runatreboot,runonce 1 \
#   # renews certificate or issues new one if it does not exist
#   podman run --replace --rm --name acme --network podman_public \
#     -v /mnt/data/managed/acme/account:/acme.sh -v /mnt/data/managed/acme/certs:/etc/haproxy \
#     docker.io/neilpang/acme.sh:latest --issue --pre-hook 'nc -lp 80 & sleep 30 ; kill $!' --server letsencrypt --standalone \
#       $(grep -oP 'use_backend .* www\.\K\S+' /etc/podman/haproxy.cfg | sed 's/^/-d /' | tr '\n' ' ') && \
#   # deploys certificate
#   podman run --replace --rm --name acme --network podman_public \
#     -v /mnt/data/managed/acme/account:/acme.sh -v /mnt/data/managed/acme/certs:/etc/haproxy \
#     docker.io/neilpang/acme.sh:latest --deploy --deploy-hook haproxy \
#       $(find /mnt/data/managed/acme/account/ -maxdepth 1 -name *_ecc -exec basename {} \; | sed 's/_ecc//' | sed 's/^/-d /' | tr '\n' ' ') && \
#   # reloads haproxy gracefully
#   podman kill -s HUP haproxy
