parity /mnt/parity/snapraid.parity

data fast-01 /mnt/pool/fast-01/
data slow-01 /mnt/pool/slow-01/

content /mnt/.snapraid.content

content /mnt/pool/fast-01/.snapraid.content
content /mnt/pool/slow-01/.snapraid.content

autosave 64
