# http://fcron.free.fr/doc/en/fcrontab.5.html

# runs once a day
%daily,random,serial * 2-8 \
  duncache --pusage 80 --source /mnt/storage/fast --target /mnt/storage/slow && \
  dsnap --max-deleted 5 --max-updated 10

# runs once on startup
@runatreboot,runonce,serial 1 \
  snapraid fix && \
  set-mounts-permissions

# starts podman containers on boot
@runas(chuck),runatreboot,runonce 1 until \
  podman-compose -f $HOME/.config/podman/compose.yaml up -d --force-recreate --remove-orphans; \
  do sleep 60; done
