version: "3"
services:
  reverse_proxy_cert:
    container_name: reverse_proxy_cert
    image: docker.io/alpine:latest
    pull_policy: always
    restart: unless-stopped
    entrypoint: /entrypoint.sh
    volumes:
      - ./reverse-proxy-cert-entrypoint.sh:/entrypoint.sh:ro
      - reverse_proxy_cert_data:/data:rw

  reverse_proxy:
    container_name: reverse_proxy
    image: docker.io/haproxy:alpine
    expose: ["80", "443"]
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - teste
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0

  reverse_proxy_tunnel_http:
    container_name: reverse_proxy_tunnel_http
    image: docker.io/jnovack/autossh:latest
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - reverse_proxy
    volumes:
      - ../.ssh/key:/id_rsa:ro
    environment:
      - SSH_REMOTE_HOST=79.72.49.218
      - SSH_REMOTE_USER=chuck
      - SSH_TARGET_HOST=reverse_proxy
      - SSH_TARGET_PORT=80
      - SSH_TUNNEL_PORT=80

  reverse_proxy_tunnel_https:
    container_name: reverse_proxy_tunnel_https
    image: docker.io/jnovack/autossh:latest
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - reverse_proxy
    volumes:
      - ../.ssh/key:/id_rsa:ro
    environment:
      - SSH_REMOTE_HOST=79.72.49.218
      - SSH_REMOTE_USER=chuck
      - SSH_TARGET_HOST=reverse_proxy
      - SSH_TARGET_PORT=443
      - SSH_TUNNEL_PORT=443

  teste:
    container_name: teste
    image: docker.io/nginx
    expose: ["80"]

volumes:
  reverse_proxy_cert_data:
