sys-kernel/gentoo-kernel-bin
sys-kernel/installkernel
sys-kernel/linux-firmware

app-admin/doas
app-admin/eclean-kernel
app-containers/podman-compose
dev-vcs/git
net-firewall/nftables
net-misc/openssh
sys-firmware/intel-microcode
sys-process/htop

sys-process/btop
