#!/bin/bash
set -eo pipefail

while [[ $# -gt 0 ]]; do
  case $1 in
  -h | --help) echo "Usage: $(basename "$0") [--hostname <hostname>] [--user <username>]" && exit 0 ;;
  --hostname) SYSTEM_HOSTNAME=$2 ;;
  --user) SYSTEM_USER=$2 ;;
  esac
  shift
  shift
done

function run_as_user() { if [[ ${EUID} -eq 0 ]]; then runuser -u "$1" -- "${@:2}"; else "${@:2}"; fi; }

SYSTEM_HOSTNAME=${SYSTEM_HOSTNAME:-$(uname --nodename)}
SYSTEM_USER=${SYSTEM_USER:-$(whoami)}

cd "/home/${SYSTEM_USER}/workspace/personal/dotfiles"
run_as_user "${SYSTEM_USER}" git fetch origin
run_as_user "${SYSTEM_USER}" git reset --hard origin/main
run_as_user "${SYSTEM_USER}" git clean --force --quiet -dx
"/home/${SYSTEM_USER}/workspace/personal/dotfiles/${SYSTEM_HOSTNAME}/maintain.sh"
