#!/bin/bash
set -eo pipefail

if [[ ${EUID} -ne 0 ]]; then
  su root -c "$0" "$@"
  exit $?
fi

dracut --force --hostonly --kver "$(eselect kernel list | grep --only-matching --perl-regexp 'linux-\K[^ ]+')" --quiet
grub-mkconfig --output=/boot/grub/grub.cfg
