#!/bin/bash

# dotfiles specific variables
export _HOST='gentoo-server-hetzner-proxy'
export _USER='chuck'

# gentoo specific variables
export _DEV='/dev/sda'
export _BOOT='/dev/sda1'
export _ROOT='/dev/sda2'

export _BOOT_SIZE='+512M'
export _ROOT_SIZE='+32G'

# dotfiles specific variables
_LAYERS=(
  # dotfiles tooling
  "layers.d/shared-dots.d"
  # root system settings
  "layers.d/gentoo-portage.d"
  "layers.d/gentoo-bootloader.d"
  "layers.d/gentoo-doas.d"
  # server settings
  "layers.d/gentoo-podman-server.d"
  # base system settings
  "layers.d/shared-bash.d"
  "layers.d/shared-git.d"
  "layers.d/shared-secrets.d"
  "layers.d/shared-ssh.d"
  # code settings and tooling
  "layers.d/shared-lazygit.d"
  "layers.d/shared-neovim.d"
  "layers.d/shared-tmux.d"
  # host specific settings
  "hosts.d/$_HOST.d"
)

function after_partitioning() {
  sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' <<EOF | fdisk "$_DEV"
    n  # create extra partition
       # choose default partition type
       # choose default partition number
       # choose default sector number
       # fills remaining disk
    p  # print partition table
    w  # write changes to disk
EOF
}
