#!/bin/bash
# shellcheck disable=SC2015 disable=SC2088 source=/dev/null
set -eou pipefail

export _DEV='/dev/nvme0n1'
export _BOOT='/dev/nvme0n1p1'
export _ROOT='/dev/nvme0n1p2'
export _HOST='gentoo-laptop-dell'
export _USER='chuck'

export _BOOT_SIZE='+1G'
export _ROOT_SIZE=' '

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# sources auxiliary functions
_IS_DOTS_UTILS_LOADED=""
source "$(dirname "$(readlink -f "$0")")/../dots-utils" >/dev/null 2>&1 ||
  source /dev/stdin <<<"$(curl -Lfs "$_DOTS_RAW_URL/dots-utils")"
[ -z "$_IS_DOTS_UTILS_LOADED" ] && echo '[E] failed to source dots-utils' && exit 1

function _main() {
  _CMD='' && [ "$#" -ge 1 ] && _CMD="$1"
  case $_CMD in

  # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
  # prepares live iso system and installs gentoo using custom script
  install) run_script 'dots-gentoo-installer' ;;

  # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
  # clears deprecated directories and links after resetting them
  sync)
    _HOME="$(get_home "$@")" && _HOST="$(get_host "$@")"
    ! is_root && echo '[E] missing required permissions' && return 1

    echo '[I] linking files...'
    run_script 'hosts.d/default.d/00-install.sh' "$@" ||
      (echo '[E] failed to install layer (default)' && return 1)
    run_script 'hosts.d/default.gentoo.d/00-install.sh' "$@" ||
      (echo '[E] failed to install layer (default.gentoo)' && return 1)
    run_script "hosts.d/host.$_HOST.d/00-install.sh" "$@" ||
      (echo "[E] failed to install layer (host.$_HOST)" && return 1)

    ! get_option '--skip-cleaning' "$@" && (
      echo '[I] cleaning empty directories and stale links...'
      run_as_root clean_directories_and_links / ||
        (echo '[E] failed to clean directories and links' && return 1)
    )

    eauto --unsupervised
    eselect news read >/dev/null 2>&1
    regenerate-bootloader

    run_as_user chuck secrets-set gpg-github-pedro-pereira-dev
    run_as_user chuck secrets-set ssh-authorized-keys
    run_as_user chuck secrets-set ssh-gentoo-hetzner-media
    run_as_user chuck secrets-set ssh-gentoo-laptop
    run_as_user chuck secrets-set ssh-github-pedro-pereira-dev
    run_as_user chuck secrets-set ssh-mercedes-github-pesoare
    run_as_user chuck secrets-import

    return 0
    ;;

  # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
  # handles unknown commands
  *) usage && return 1 ;;
  esac
}
_main "$@"
