#!/bin/bash
# shellcheck disable=SC2015 disable=SC2088 source=/dev/null
set -eou pipefail

export _DEV='/dev/sda'
export _BOOT='/dev/sda1'
export _ROOT='/dev/sda2'
export _HOST='gentoo-server-hetzner-proxy'
export _USER='chuck'

export _BOOT_SIZE='+512M'
export _ROOT_SIZE=' '
export _TABLE_TYPE='--mbr'

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# sources auxiliary functions
_IS_DOTS_UTILS_LOADED=""
source "$(dirname "$(readlink -f "$0")")/../dots-utils" >/dev/null 2>&1 ||
  source /dev/stdin <<<"$(curl -Lfs "$_DOTS_RAW_URL/dots-utils")"
[ -z "$_IS_DOTS_UTILS_LOADED" ] && echo '[E] failed to source dots-utils' && exit 1

function _main() {
  _CMD='' && [ "$#" -ge 1 ] && _CMD="$1"
  case $_CMD in

  # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
  # prepares live iso system and installs gentoo using custom script
  install)
    _HOST="$(get_host "$@")"
    run_script 'dots-gentoo-installer' "$_TABLE_TYPE" ||
      (echo "[E] failed to install gentoo to ($_HOST)" && return 1)
    return 0
    ;;

  # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
  # clears deprecated directories and links after resetting them
  sync)
    _HOME="$(get_home "$@")" && _HOST="$(get_host "$@")"
    ! is_root && echo '[E] missing required permissions' && return 1

    run_script 'hosts.d/default.d/install.sh' "$@" ||
      (echo '[E] failed to install layer (default)' && return 1)
    run_script 'hosts.d/default.gentoo.d/install.sh' "$@" ||
      (echo '[E] failed to install layer (default.gentoo)' && return 1)
    run_script "hosts.d/host.$_HOST.d/install.sh" "$@" ||
      (echo "[E] failed to install layer (host.$_HOST)" && return 1)

    ! get_option '--skip-cleaning' "$@" && (
      run_as_root clean_directories_and_links / ||
        (echo '[E] failed to clean directories and links' && return 1)
    )
    return 0
    ;;

  # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
  # handles unknown commands
  *) usage && return 1 ;;
  esac
}
_main "$@"
