#!/bin/bash
set -eou pipefail

echo "[I] installing from repositories:
- _DOTS_DIR: $_DOTS_DIR
- _DOTS_RAW_URL: $_DOTS_RAW_URL
- _GENTOO_RAW_URL: $_GENTOO_RAW_URL"
echo "[I] installing to system:
- _HOST: $_HOST
- _USER: $_USER"
echo "[I] installing on the device $_DEV:
- _BOOT: $_BOOT (size: '$_BOOT_SIZE')
- _ROOT: $_ROOT (size: '$_ROOT_SIZE')"
echo "[I] data from device $_DEV will be erased"
read -r -p 'Do you want to continue? [Y/n]: ' _CONFIRMATION && echo ''
[[ $_CONFIRMATION == 'n' || $_CONFIRMATION == 'N' ]] && return 0
# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----

# prepares device layout for gentoo installation
echo "[I] preparing device '$_DEV'..."
wipefs -a "$_DEV"
if [ -d '/sys/firmware/efi' ]; then
  echo '[I] creating GPT table...'
  sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' <<EOF | fdisk "$_DEV"
    g  # create empty gpt partition table
    n  # create boot partition
       # choose default partition number
       # choose default sector
    $_BOOT_SIZE
    y  # delete partition signature
    t  # choose partition type
    1  # choose efi system
    n  # create root partition
       # choose default partition number
       # choose default sector
    $_ROOT_SIZE
    y  # delete partition signature
    t  # choose partition type
       # choose default partition number
    23 # choose linux root
    p  # print partition table
    w  # write changes to disk
EOF
else
  echo '[I] creating MBR table...'
  sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' <<EOF | fdisk "$_DEV"
    o  # create empty mbr partition table
    n  # create boot partition
       # choose default partition type
       # choose default partition number
       # choose default sector number
    $_BOOT_SIZE
    a  # mark partition as bootable
    n  # create root partition
       # choose default partition type
       # choose default partition number
       # choose default sector number
    $_ROOT_SIZE
    p  # print partition table
    w  # write changes to disk
EOF
fi
# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----

# installs gentoo to the device
echo "[I] using gentoo-installer script..."
curl -Lfs "$_GENTOO_RAW_URL/install.sh" | bash -s -- \
  --hostname "$_HOST" \
  --boot "$_BOOT" \
  --root "$_ROOT" \
  --password "$_PASSWORD" \
  --keymap 'pt-latin9' \
  --timezone 'Europe/Lisbon'
# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----

# creates user account and sets up system using dotfiles
chroot /mnt /bin/bash <<EOF
env-update && source /etc/profile
useradd -m -G wheel -s /bin/bash "$_USER"
echo "$_USER:$_PASSWORD" | chpasswd
emerge --ask=n --noreplace dev-vcs/git
curl -Lfs "$_DOTS_RAW_URL/dots" | bash -s -- update
/home/$_USER/$_DOTS_DIR/dots sync
EOF
