#!/bin/bash
# shellcheck disable=SC2015

# debug variable to validate if this file was sourced
export _IS_DOTS_UTILS_LOADED="true"

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# checks for the existence of a command in the system path
# arguments:
#   $1 - the name of the command to check for (e.g., 'git', 'docker', 'python3')
# returns:
#   0 (success) if the command is found
#   1 (failure) if the command is not found
function check_command() { which "$1" >/dev/null 2>&1; }

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# gets the first non-root user with privileges from system
# arguments:
#   none
# returns:
#   the user id if it exists, printed to standard output
#   0 (success) if user is found
#   1 (failure) if user is not found
function get_first_wheel_user() { grep '^wheel:' /etc/group | tr ',' '\n' | grep -v 'root' | head -n 1 | grep '.'; }

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# gets the value of a specific command-line option
# arguments:
#   $1 - the name of the option to find (e.g., "--path")
#   $@ - all subsequent command-line arguments to search through
# returns:
#   the value of the option if it exists, printed to standard output
#   0 (success) if the option is found
#   1 (failure) if the option is not found
function get_option() {
  _OPTION="$1" && shift
  while [[ "$#" -gt 0 ]]; do
    _ARG="$1" && shift
    if [[ "$_ARG" == "$_OPTION" ]]; then
      [[ "$#" -gt 0 ]] && ! [[ "$1" =~ ^- ]] && echo "$1"
      return 0
    fi
  done
  return 1
}

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# gets the user id executing the script
# arguments:
#   $@ - the parent script arguments
# returns:
#   the user id, printed to standard output
#   0 (success) if user is found
#   1 (failure) if user is not found
function get_user() {
  _USER="$(get_option "--user" "$@")" || true
  [[ -n "$_USER" ]] && echo "$_USER" && return 0
  is_root && get_first_wheel_user && return 0 || true
  ! is_root && whoami && return 0 || true
  return 1
}

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# gets the user home directory path executing the script
# arguments:
#   $@ - the parent script arguments
# returns:
#   the user home directory path, printed to standard output
#   0 (success) if path is found
#   1 (failure) if path is not found
function get_home() {
  _USER="$(get_user "$@")" || return 1
  [ "$(uname)" == 'Darwin' ] && echo "/Users/$_USER" && return 0 || true
  [ "$(uname)" == 'Linux' ] && echo "/home/$_USER" && return 0 || true
  return 1
}

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# gets the host of the system executing the script
# arguments:
#   $@ - the parent script arguments
# returns:
#   the host, printed to standard output
#   0 (success) if host is found
#   1 (failure) if host is not found
function get_host() {
  _HOST="$(get_option "--host" "$@")" || true
  [[ -n "$_HOST" ]] && echo "$_HOST" && return 0
  [ "$(uname)" == 'Darwin' ] && hostname && return 0 || true
  [ "$(uname)" == 'Linux' ] && cat /etc/hostname 2>/dev/null && return 0 || true
  return 1
}

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# checks if the current user is root
# arguments:
#   none
# returns:
#   0 (success) if the user id is 0 - root user
#   1 (failure) if the user id is not 0 - non-root user
function is_root() { test $EUID -eq 0; }

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# runs a command as the root user
# arguments:
#   $@ - the command and its arguments to be executed with root privileges
#        (e.g., 'emerge dev-vcs/git', 'nano /etc/hosts')
# returns:
#   the exit status of the executed command
function run_as_root() {
  if is_root; then
    "$@"
  elif check_command doas; then
    doas "$@"
  elif check_command sudo; then
    sudo "$@"
  else
    return 1
  fi
}

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# runs a command as a specified non-root user
# arguments:
#   $1 - the name of the user to switch to (e.g., 'myuser').
#   $@ - all subsequent arguments, which form the command and its arguments
#        to be executed (e.g., 'ls -l /home/myuser')
# returns:
#   the exit status of the executed command
function run_as_user() { if is_root; then su "$1" -c "${*:2}"; else "${@:2}"; fi; }

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# runs a script from the local filesystem or directly from github
# arguments:
#   $1 - the relative path to the script to execute from the base dotfiles directory
#   $@ - all subsequent arguments, which form the command and its arguments
#        to be executed (e.g., 'install', 'sync')
# returns:
#   the exit status of the executed command
#   1 (failure) if any failure occurs
function run_script() {
  _HOME="$(get_home "$@")" || return 1
  _LOCAL_SCRIPT="$_HOME/$_DOTS_DIR/$1"
  _REMOTE_SCRIPT="$_DOTS_RAW_URL/$1"
  if [ -f "$_LOCAL_SCRIPT" ]; then
    bash "$_LOCAL_SCRIPT" "${*:2}"
  elif curl -ILs "$_REMOTE_SCRIPT" >/dev/null; then
    curl -Lfs "$_REMOTE_SCRIPT" | bash -s -- "${*:2}"
  else
    return 1
  fi
}
