version: "3"
services:
  reverse_proxy:
    container_name: reverse_proxy
    image: docker.io/haproxy:alpine
    depends_on:
      - webpage_test
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/remote-4620.duckdns.org.pem:/etc/haproxy/certs/remote-4620.duckdns.org.pem:ro
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "443:443"

  webpage_test:
    container_name: webpage_test
    image: docker.io/nginx:alpine
    volumes:
      - ./nginx:/usr/share/nginx/html:ro
    expose:
      - "80"
