#!/bin/bash

SYSTEM_USER=$(whoami)

HOME_DIR="/home/${SYSTEM_USER}"
GPG_DIR="${HOME_DIR}/.gnugpg"
SSH_DIR="${HOME_DIR}/.ssh"

[[ ${EUID} -eq 0 ]] && echo 'Aborting... cannot run as root!' && exit 1
[[ ! -d ${DOTFILES_SECRETS_DIR} ]] && echo 'Aborting... dotfiles-secrets was not cloned!' && exit 1

gpgconf --kill gpg-agent
rm -rf "${GPG_DIR}"
gpg --list-secret-keys --keyid-format=long >/dev/null 2>&1
[[ -f ${GPG_DIR}/common.conf ]] && sed -i 's/use-keyboxd/#use-keyboxd/g' "${GPG_DIR}/common.conf"
find "${SSH_DIR}" -type f -name '*-gpg' -exec gpg --import '{}' ';'

KEYS=$(gpg --list-keys --fingerprint --with-colons | sed -E -n -e 's/^fpr:::::::::([0-9A-F]+):$/\1:6:/p')
[[ -n ${KEYS} ]] && gpg --import-ownertrust "${KEYS}"
