#!/bin/bash
set -eo pipefail

[[ ${EUID} -eq 0 ]] && echo 'Aborting... cannot run as root!' && exit 1
[[ $# -ne 1 ]] && echo "Usage: $(basename "$0") <secret-name>" && exit 1

SYSTEM_USER=$(whoami)

DOTFILES_SECRETS_DIR="/home/${SYSTEM_USER}/workspace/personal/dotfiles-secrets"
SECRETS_DIR="/home/${SYSTEM_USER}/.ssh/secrets"

[[ ! -d ${DOTFILES_SECRETS_DIR} ]] && echo 'Aborting... dotfiles-secrets was not cloned!' && exit 1
[[ ! -d ${SECRETS_DIR}/$1 ]] && echo "Aborting... ${SECRETS_DIR}/$1 does not exist!" && exit 1

if [[ -f ${SECRETS_DIR}/$1/private.asc ]]; then
  GPG_KEY=$(gpg --dry-run --import-options import-show --with-colons --import "${SECRETS_DIR}/$1/private.asc" 2>&1 | grep --only-matching --perl-regexp 'fpr:*\K(.*)(?=:)')
  if [[ -n ${GPG_KEY} ]]; then
    if gpg --list-keys | grep --only-matching --perl-regexp "${GPG_KEY}" >/dev/null; then
      gpg --batch --delete-secret-key --yes --pinentry-mode loopback "${GPG_KEY}"
      gpg --batch --delete-key --yes --pinentry-mode loopback "${GPG_KEY}"
    fi
    rm --force "${SECRETS_DIR}/$1/private.asc"
    rm --force "${SECRETS_DIR}/$1/public.asc"
  fi
fi

rm --force --recursive "${SECRETS_DIR:?}/$1"
