#!/bin/bash
set -eo pipefail

[[ ${EUID} -eq 0 ]] && echo 'Aborting... cannot run as root!' && exit 1
[[ $# -ne 1 ]] && echo "Usage: $(basename "$0") <secret-name>" && exit 1

SYSTEM_USER=$(whoami)

DOTFILES_SECRETS_DIR="/home/${SYSTEM_USER}/workspace/personal/dotfiles-secrets"
SECRETS_DIR="/home/${SYSTEM_USER}/.ssh/secrets"
SECRET_TAR=$(mktemp)

[[ ! -d ${DOTFILES_SECRETS_DIR} ]] && echo 'Aborting... dotfiles-secrets was not cloned!' && exit 1
[[ -d ${SECRETS_DIR}/$1 ]] && echo "Aborting... ${SECRETS_DIR}/$1 already exists!" && exit 0
[[ ! -f ${DOTFILES_SECRETS_DIR}/$1.tar.enc ]] && echo "Aborting... ${DOTFILES_SECRETS_DIR}/$1.tar.enc does not exist!" && exit 1

echo "Setting up ${DOTFILES_SECRETS_DIR}/$1.tar.enc..."
mkdir --parents "${SECRETS_DIR}"
gpg --pinentry-mode loopback --quiet --decrypt "${DOTFILES_SECRETS_DIR}/$1.tar.enc" >"${SECRET_TAR}"
tar --directory "${SECRETS_DIR}" --extract --file "${SECRET_TAR}"
rm --force "${SECRET_TAR}"
