#!/bin/bash
set -eo pipefail

[[ ${EUID} -eq 0 ]] && echo 'Aborting... cannot run as root!' && exit 1

SYSTEM_USER=$(whoami)

DOTFILES_SECRETS_DIR="/home/${SYSTEM_USER}/workspace/personal/dotfiles-secrets"
SECRETS_DIR="/home/${SYSTEM_USER}/.ssh/secrets"

[[ ! -d ${DOTFILES_SECRETS_DIR} ]] && echo 'Aborting... dotfiles-secrets was not cloned!' && exit 1

mkdir --parents "${SECRETS_DIR}"
find "${SECRETS_DIR}" -type f -name 'private.asc' -exec gpg --import '{}' ';'
gpg --fingerprint --list-keys |
  grep pub --after-context=1 |
  grep --extended-regexp --invert-match 'pub|--' |
  tr --delete ' ' |
  awk 'BEGIN { FS = "\n" } ; { print $1":6:" } ' |
  gpg --import-ownertrust
