#!/bin/bash
set -eo pipefail

[[ ${EUID} -eq 0 ]] && echo 'Aborting... cannot run as root!' && exit 1
[[ $# -ne 1 ]] && echo "Usage: $(basename "$0") <secret-name>" && exit 1

SYSTEM_USER=$(whoami)

DOTFILES_SECRETS_DIR="/home/${SYSTEM_USER}/workspace/personal/dotfiles-secrets"
SECRETS_DIR="/home/${SYSTEM_USER}/.ssh/secrets"
TEMP_DIR=$(mktemp --directory)

[[ ! -d ${DOTFILES_SECRETS_DIR} ]] && echo 'Aborting... dotfiles-secrets was not cloned!' && exit 1
[[ ! -d ${SECRETS_DIR}/$1 ]] && echo "Aborting... ${SECRETS_DIR}/$1 does not exist!" && exit 1

cd "${SECRETS_DIR}"
tar --create --file "${TEMP_DIR}/$1.tar" --gzip "$1"
gpg --cipher-algo AES256 --pinentry-mode loopback --symmetric "${TEMP_DIR}/$1.tar"
mv --force "${TEMP_DIR}/$1.tar.gpg" "${DOTFILES_SECRETS_DIR}/$1.tar.enc"
rm --force --recursive "${TEMP_DIR}"
