#!/bin/bash

SYSTEM_USER=$(whoami)

HOME_DIR="/home/${SYSTEM_USER}"
DOTFILES_SECRETS_DIR="${HOME_DIR}/workspace/personal/dotfiles-secrets"
SECRETS_DIR="${HOME_DIR}/.ssh/secrets"

[[ ${EUID} -eq 0 ]] && echo 'Aborting... cannot run as root!' && exit 1
[[ ! -d ${DOTFILES_SECRETS_DIR} ]] && echo 'Aborting... dotfiles-secrets was not cloned!' && exit 1
[[ $# -ne 1 ]] && echo -e "\nUsage: $(basename "$0") <secret-name>\n" && exit 1

SECRET_NAME=$1
SECRET_TAR_GPG=${DOTFILES_SECRETS_DIR}/${SECRET_NAME}.tar.gpg
SECRET_DIR=${SECRETS_DIR}/${SECRET_NAME}
SECRET_TAR=${SECRET_DIR}/${SECRET_NAME}.tar

[[ ! -f ${SECRET_TAR_GPG} ]] && echo "Aborting... ${SECRET_TAR_GPG} does not exist!" && exit 1
mkdir --parents "${SECRET_DIR}"
gpg --pinentry-mode loopback --decrypt "${SECRET_TAR_GPG}" >"${SECRET_TAR}"
tar -xf "${SECRET_TAR}" -C "${SECRET_DIR}"
rm -rf "${SECRET_TAR}"
