#!/bin/bash
# shellcheck disable=SC2015 disable=SC2088 source=/dev/null
set -eou pipefail

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# sources auxiliary functions
_IS_DOTS_UTILS_LOADED=""
source "$(dirname "$(readlink -f "$0")")/../dots-utils" >/dev/null 2>&1 ||
  source /dev/stdin <<<"$(curl -Lfs "$_DOTS_RAW_URL/dots-utils")"
[ -z "$_IS_DOTS_UTILS_LOADED" ] && echo '[E] failed to source dots-utils' && exit 1

function _main() {
  case $1 in

  # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
  # clears setup and applies dotfiles to system
  sync)
    _HOME="$(get_home "$@")" && _HOST="$(get_host "$@")"
    is_root && echo '[E] failed because it should not run as root' && return 1
    stow_directory 'default' ||
      (echo "[E] failed to symlink files for (default)" && return 1)
    stow_directory "$_HOST" ||
      (echo "[E] failed to symlink files for ($_HOST)" && return 1)
    clean_directories_and_links "$_HOME" ||
      (echo '[E] failed to clean directories and links' && return 1)
    return 0
    ;;

  # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
  # handles unknown commands
  *) echo "[E] unknown command ($1)" && return 1 ;;
  esac
}
_main "$@"
