#!/bin/bash
# shellcheck disable=SC2015 disable=SC2088 source=/dev/null
set -eou pipefail

# constants
export _DEV='/dev/sda'
export _BOOT='/dev/sda1'
export _ROOT='/dev/sda2'
export _HOST='gentoo-server-hetzner-proxy'
export _USER='chuck'

export _BOOT_SIZE='+512M'
export _ROOT_SIZE=' '
export _TABLE_TYPE='--mbr'

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# sources auxiliary functions
_IS_DOTS_UTILS_LOADED=""
source "$(dirname "$(readlink -f "$0")")/../dots-utils" >/dev/null 2>&1 ||
  source /dev/stdin <<<"$(curl -Lfs "$_DOTS_RAW_URL/dots-utils")"
[ -z "$_IS_DOTS_UTILS_LOADED" ] && echo '[E] failed to source dots-utils' && exit 1

function _main() {
  case $1 in

  # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
  # sets up live iso system and runs custom gentoo installation script
  install)
    run_script 'dots-gentoo-installer' "$_TABLE_TYPE" ||
      (echo "[E] failed to install gentoo to ($_HOST)" && return 1)
    return 0
    ;;

  # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
  # clears setup and applies dotfiles to system
  sync)
    echo "gentoo sync in hetzner proxy"
    return 0
    ;;

  # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
  # handles unknown commands
  *) echo "[E] unknown command ($1)" && return 1 ;;
  esac
}
_main "$@"
