[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = true
option_as_alt = "Both"
[window.padding]
x = 12
y = 2

[font]
size = 12

[font.normal]
family = "JetbrainsMono NFM"

[cursor]
blink_interval = 250
blink_timeout = 0

[cursor.style]
blinking = "Always"
