#!/bin/bash
cleanup() { umount -R /mnt/restore; }
trap cleanup EXIT

[ "$EUID" -eq 0 ] || { echo 'Required to run as root' && exit 1; }

cat >/etc/apt/sources.list.d/pve-install-repo.sources <<EOL
Types: deb
URIs: http://download.proxmox.com/debian/pve
Suites: trixie
Components: pve-no-subscription
Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg
EOL

! test -f /usr/share/keyrings/proxmox-archive-keyring.gpg &&
  curl -L https://enterprise.proxmox.com/debian/proxmox-archive-keyring-trixie.gpg -o /usr/share/keyrings/proxmox-archive-keyring.gpg
echo '136673be77aba35dcce385b28737689ad64fd785a797e57897589aed08db6e45 /usr/share/keyrings/proxmox-archive-keyring.gpg' |
  sha256sum --check --status || { echo 'SHA256 mismatch' && exit 1; }
echo '77c8b1166d15ce8350102ab1bca2fcbf /usr/share/keyrings/proxmox-archive-keyring.gpg' |
  md5sum --check --status || { echo 'MD5 mismatch' && exit 1; }

apt update
apt install -y arch-install-scripts jq proxmox-backup-client

echo && lsblk && echo
PARTS=$(lsblk -lno NAME,TYPE -p | awk '$2=="part" {print $1}')
[ -z "$PARTS" ] && { echo 'No partitions found' && exit 1; }
PS3='Enter number: '

mkdir -p /mnt/restore
mountpoint -q /mnt/restore || {
  echo 'Select the partition to mount on /mnt/restore:'
  select RESTORE_PART in $PARTS; do
    [ -n "$RESTORE_PART" ] && break || echo 'Invalid selection'
  done </dev/tty
  echo
  mount "$RESTORE_PART" /mnt/restore || { echo 'Mount failed' && exit 1; }
}

[ -z "$PBS_PASSWORD" ] &&
  read -r -p 'Enter PBS repository with current user (root@pam@pbs:datastore): ' REPOSITORY </dev/tty &&
  : "${REPOSITORY:?PBS repository is required}" &&
  export PBS_REPOSITORY=$REPOSITORY
[ -z "$PBS_PASSWORD" ] &&
  read -rs -p 'Enter PBS current user password: ' PASSWORD </dev/tty &&
  : "${PASSWORD:?PBS user password is required}" &&
  echo &&
  export PBS_PASSWORD=$PASSWORD
[ -z "$PBS_FINGERPRINT" ] &&
  read -r -p 'Enter PBS fingerprint: ' FINGERPRINT </dev/tty &&
  : "${FINGERPRINT:?PBS fingerprint is required}" &&
  export PBS_FINGERPRINT=$FINGERPRINT

PS3='Enter number: '
echo 'Select the namespace to work with:'
NAMESPACES=$(proxmox-backup-client namespace list 2>/dev/null | grep '^local')
select NAMESPACE in $NAMESPACES; do
  [ -n "$NAMESPACE" ] && break || echo 'Invalid selection'
done </dev/tty
echo

SNAPSHOTS=$(proxmox-backup-client snapshot list --ns "$NAMESPACE" --output-format json 2>/dev/null |
  jq -r 'sort_by(.["backup-time"]) | reverse | .[] | select(.["backup-type"] == "host") | "\(.["backup-type"])/\(.["backup-id"])/\(.["backup-time"] | strftime("%Y-%m-%dT%H:%M:%SZ"))"')
[ -z "$SNAPSHOTS" ] && echo "No 'host' snapshots found" && exit 1

PS3='Enter number: '
echo 'Select the host snapshot to restore:'
select SNAPSHOT in $SNAPSHOTS; do
  [ -n "$SNAPSHOT" ] && break || echo 'Invalid selection'
done </dev/tty
echo

echo -n "Restore $SNAPSHOT to /mnt/restore? (y/N): "
read -r CONFIRM </dev/tty
[[ "$CONFIRM" =~ ^[yY]$ ]] || { echo 'Restorate cancelled' && echo && exit 1; }
echo

rm -fr /mnt/restore/{*,.*}
proxmox-backup-client restore "$SNAPSHOT" root.pxar /mnt/restore --ns "$NAMESPACE" ||
  { echo 'Restorate failed' && echo && exit 1; }

echo && lsblk && echo
mkdir -p /mnt/restore/boot/efi
mountpoint -q /mnt/restore/boot/efi || {
  echo 'Select the ESP/EFI partition to mount on /mnt/restore/boot/efi:'
  select EFI_PART in $PARTS; do
    [ -n "$EFI_PART" ] && break || echo 'Invalid selection'
  done </dev/tty
  echo
  mount "$EFI_PART" /mnt/restore/boot/efi || { echo 'EFI mount failed' && exit 1; }
}
rm -fr /mnt/restore/boot/efi/{*,.*}

arch-chroot /mnt/restore /bin/bash -c 'update-grub && update-initramfs -u && proxmox-boot-tool reinit && exit'
