version: "3"
services:
  haproxy:
    image: docker.io/haproxy:alpine
    ports:
      - "443:443"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:z
      - /etc/haproxy/certs/remote-4620.duckdns.org.pem:/etc/haproxy/certs/remote-4620.duckdns.org.pem:z
    cap_add:
      - NET_BIND_SERVICE
