[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = true
option_as_alt = "OnlyLeft"
[window.padding]
x = 8
y = 4

[font]
size = 12

[font.normal]
family = "Jetbrainsmono Nerd Font"

[cursor]
blink_interval = 250
blink_timeout = 0

[colors.primary]
background = "#000000"
foreground = "#d2d1e6"

[colors.normal]
black = "#2e3440"
red = "#ff3242"
green = "#44bc44"
yellow = "#ff9400"
blue = "#0883ff"
magenta = "#d930d9"
cyan = "#00d8eb"
white = "#d8dee9"

[colors.bright]
black = "#4c566a"
red = "#ff6e6e"
green = "#9ec875"
yellow = "#ffaf00"
blue = "#47bfe6"
magenta = "#d294ff"
cyan = "#8ae2f0"
white = "#eceff4"
