app-admin/doas # required to manage users permissions
dev-vcs/git # required by gentoo git overlays
net-firewall/nftables # required to implement firewall
sys-kernel/installkernel # required to have grub bootloader
