# default runlevel
id:3:initdefault:
# system initialization
si::sysinit:/sbin/openrc sysinit
rc::bootwait:/sbin/openrc boot

# runlevel configurations
l0u:0:wait:/sbin/telinit u
l0:0:wait:/sbin/openrc shutdown
l0s:0:wait:/sbin/halt.sh
l1:1:wait:/sbin/openrc single
l2:2:wait:/sbin/openrc nonetwork
l3:3:wait:/sbin/openrc default
l4:4:wait:/sbin/openrc default
l5:5:wait:/sbin/openrc default
l6u:6:wait:/sbin/telinit u
l6:6:wait:/sbin/openrc reboot
l6r:6:wait:/sbin/reboot -dkn

# single-user mode
su0:S:wait:/sbin/openrc single
su1:S:wait:/sbin/sulogin

# terminals
c1:12345:respawn:/sbin/agetty --noclear 38400 tty1 linux
# c2:2345:respawn:/sbin/agetty 38400 tty2 linux

# ctrl+alt+del action
ca:12345:ctrlaltdel:/sbin/shutdown -r now
# display manager
x:a:once:/usr/bin/startDM

# Architecture specific features
# f0:12345:respawn:/sbin/agetty 9600 ttyAMA0 vt100
