#!/bin/bash

[[ $# -gt 1 ]] && echo "Usage: $(basename "$0") [--unsupervised]" && exit 1
[[ ${EUID} -ne 0 ]] && doas "$0" "$@" && exit $?

eupdate
edeclare "$([[ $1 == '--unsupervised' ]] && echo '--unsupervised' || echo '')"
eupgrade "$([[ $1 == '--unsupervised' ]] && echo '--unsupervised' || echo '')"
edelete "$([[ $1 == '--unsupervised' ]] && echo '--unsupervised' || echo '')"
