#!/bin/bash

[[ $# -gt 1 ]] && echo "Usage: $(basename "$0") [--unsupervised]" && exit 1
if [[ ${EUID} -ne 0 ]]; then
  su root -c "$0" "$@"
  exit $?
fi

eupdate
edeclare "$([[ $1 == '--unsupervised' ]] && echo '--unsupervised' || echo '')"
eupgrade "$([[ $1 == '--unsupervised' ]] && echo '--unsupervised' || echo '')"
edelete "$([[ $1 == '--unsupervised' ]] && echo '--unsupervised' || echo '')"
