#!/bin/bash
set -eo pipefail

[[ $# -gt 1 ]] && echo "Usage: $(basename "$0") [--unsupervised]" && exit 1
[[ ${EUID} -ne 0 ]] && su root -c "$0" "$@" && exit $?

emerge --ask="$([[ $1 == '--unsupervised' ]] && echo 'n' || echo 'y')" --depclean
command -v eclean-dist >/dev/null 2>&1 && eclean-dist --deep
command -v eclean-pkg >/dev/null 2>&1 && eclean-pkg --deep
command -v eclean-kernel >/dev/null 2>&1 && eclean-kernel -n 2
