#!/bin/bash
set -eo pipefail

[[ $# -gt 1 ]] && echo "Usage: $(basename "$0") [--unsupervised]" && exit 1
[[ ${EUID} -ne 0 ]] && doas "$0" "$@" && exit $?

emerge --ask="$([[ $1 == '--unsupervised' ]] && echo 'n' || echo 'y')" --backtrack=30 --deep --newuse --update --verbose --with-bdeps=y @world
