#!/bin/bash
set -eo pipefail

[[ ${EUID} -eq 0 ]] && echo 'Aborting... cannot run as root!' && exit 1
[[ $# -ne 1 ]] && echo "Usage: $(basename "$0") <secret-name>" && exit 1
[[ ! -d /home/$(whoami)/workspace/personal/dotfiles-secrets ]] && echo 'Aborting... dotfiles-secrets was not cloned!' && exit 1
[[ ! -d /home/$(whoami)/.ssh/secrets/$1 ]] && echo "Aborting... /home/$(whoami)/.ssh/secrets/$1 does not exist!" && exit 1

TEMP_DIR=$(mktemp --directory)

cd "/home/$(whoami)/.ssh/secrets"
tar --create --file "${TEMP_DIR}/$1.tar" --gzip "$1"
gpg --cipher-algo AES256 --pinentry-mode loopback --symmetric "${TEMP_DIR}/$1.tar"
mv --force "${TEMP_DIR}/$1.tar.gpg" "/home/$(whoami)/workspace/personal/dotfiles-secrets/$1.tar.enc"
rm --force --recursive "${TEMP_DIR}"

# gpg --symmetric --cipher-algo AES256 --s2k-digest-algo SHA512 --s2k-count 65011712 secrets.txt
