#!/usr/bin/nft -f
table inet early_filter {
  chain input {
    type filter hook input priority 0;
    # invalid packets
    ct state invalid drop
  }
}
table inet default_filter {
  chain forward {
    type filter hook forward priority 2; policy drop;
  }
  chain input {
    type filter hook input priority 2; policy drop;
    # loopback and established connections
    iif lo accept
    ct state established,related accept
    # icmp
    ip protocol icmp icmp type echo-request limit rate 4/second accept
    ip protocol icmp icmp type { destination-unreachable, echo-reply, parameter-problem, time-exceeded } accept
  }
  chain output {
    type filter hook output priority 2; policy accept;
  }
}
