#!/bin/bash
# shellcheck source=/dev/null
set -eou pipefail

# constants
export _DOTS_RAW_URL='https://raw.githubusercontent.com/pedro-pereira-dev/dotfiles/refs/heads/main'
export _GENTOO_RAW_URL='https://raw.githubusercontent.com/pedro-pereira-dev/gentoo-installer/refs/heads/main'

export _DEV='/dev/sda'
export _BOOT='/dev/sda1'
export _ROOT='/dev/sda2'
export _HOST='gentoo-server-hetzner-proxy'
export _USER='chuck'

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# deletes all partitions in the system device
# and creates defined layout: 512 MB for boot and rest for root
wipefs -a "$_DEV"
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' <<EOF | fdisk "$_DEV"
    o  # create empty mbr partition table
    n  # create boot partition
       # choose default partition type
       # choose default partition number
       # choose default sector number
    +512M
    a  # mark partition as bootable
    n  # create root partition
       # choose default partition type
       # choose default partition number
       # choose default sector number
       # fill disk with new partition
    p  # print partition table
    w  # write changes to disk
EOF

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# sources templated installation
curl -Lfs "$_DOTS_RAW_URL/dots-gentoo-installer" | bash
