#!/bin/bash
# shellcheck source=/dev/null
set -eou pipefail

# constants
export _DOTS_RAW_URL='https://raw.githubusercontent.com/pedro-pereira-dev/dotfiles/refs/heads/main'
export _GENTOO_RAW_URL='https://raw.githubusercontent.com/pedro-pereira-dev/gentoo-installer/refs/heads/main'

export _DEV='/dev/nvme0n1'
export _BOOT='/dev/nvme0n1p1'
export _ROOT='/dev/nvme0n1p2'
export _HOST='gentoo-laptop-dell'
export _USER='chuck'

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# deletes all partitions in the system device
# and creates defined layout: 512 MB for boot and rest for root
wipefs -a "$_DEV"
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' <<EOF | fdisk "$_DEV"
    g  # create empty gpt partition table
    n  # create boot partition
       # choose default partition number
       # choose default sector
    +512M
    t  # choose partition type
    1  # choose efi system
    n  # create root partition
       # choose default partition number
       # choose default sector
       # fill disk with new partition
    t  # choose partition type
       # choose default partition number
    23 # choose linux root
    p  # print partition table
    w  # write changes to disk
EOF

# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
# sources templated installation
curl -Lfs "$_DOTS_RAW_URL/dots-gentoo-installer" | bash
