#!/bin/bash

# checks arguments, prints usage and prepares variables
[[ $# -gt 1 ]] && echo 'Usage: regenerate-bootloader [--unsupervised]' && exit 1
[[ $1 == '--unsupervised' ]] && UNSUPERVISED=$1

# defines flags checking functions
function is_unsupervised() { [[ ! -z ${UNSUPERVISED} ]] && return 0 || return 1; }

# defines permissions handling functions
function is_root() { [[ ${EUID} -eq 0 ]] && return 0 || return 1; }
function run_as_root() { if is_root; then ${@:2}; else ${@:1}; fi; }

# defines requirements checking functions
function check_command() { for CHECK_DEP in $@; do [[ -z $(command -v ${CHECK_DEP}) ]] && echo "Missing command: ${CHECK_DEP}" && exit 1; done; }
function confirm_command() {
  read -p "${1:-Are you sure you want to continue?} [Y/n] " CONFIRMATION_DIALOG && echo ''
  [[ ${CONFIRMATION_DIALOG} == 'n' || ${CONFIRMATION_DIALOG} == 'N' ]] && return 1 || return 0
}

# checks required dependencies
check_command doas dracut eselect grub-mkconfig
# regenerates initramfs and bootloader
if ! is_unsupervised && ! confirm_command 'Regenerate initramfs and bootloader?'; then exit 0; fi
run_as_root doas dracut --force --quiet --kver $(eselect kernel list | grep '*' | grep -o 'linux-.* ' | sed 's/linux-//g') &&
  run_as_root doas grub-mkconfig -o /boot/grub/grub.cfg
