# vscode essentials
asvetliakov.vscode-neovim            # neovim interface
be5invis.vscode-custom-css           # ui customization
equinusocio.vsc-material-theme-icons # icons
franzgollhammer.spacecat             # colorscheme

# utils
usernamehw.errorlens # errors highlight

# shell / bash
foxundermoon.shell-format     # formatter
mads-hartmann.bash-ide-vscode # language server
rogalmic.bash-debug           # debugger
timonwong.shellcheck          # linter

# vue
dbaeumer.vscode-eslint # linter
vue.volar              # language server

# miscellaneous
ryuta46.multi-command # command pallette
