#!/usr/bin/nft -f
table inet default {
  chain forward { type filter hook forward priority filter; policy drop; }
  chain output { type filter hook output priority filter; policy accept; }

  chain input {
    type filter hook input priority filter
    policy drop

    ct state { established,related } accept
    iif lo accept

    ct state invalid drop
    iif != lo ip daddr 127.0.0.0/8 drop
    ip frag-off & 0x3fff != 0 drop

    icmp type echo-request limit rate 2/second burst 4 packets accept
    icmp type { destination-unreachable,echo-reply,time-exceeded } accept
  }
}

