USE=""

#CPU_FLAGS_X86=""
#VIDEO_CARDS=""
#INPUT_DEVICES=""

#MAKEOPTS="-j[X] -l[X+1]" # X = min(RAM/2GB, threads)
EMERGE_DEFAULT_OPTS="--ask --verbose --quiet-build"
FEATURES="getbinpkg binpkg-request-signature"

COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"
GRUB_PLATFORMS="efi-64"
LC_MESSAGES=C.utf8
GENTOO_MIRRORS="https://mirrors.ptisp.pt/gentoo/ \\
    http://mirrors.ptisp.pt/gentoo/ \\
    https://ftp.rnl.tecnico.ulisboa.pt/pub/gentoo/gentoo-distfiles/ \\
    http://ftp.rnl.tecnico.ulisboa.pt/pub/gentoo/gentoo-distfiles/ \\
    ftp://ftp.rnl.tecnico.ulisboa.pt/pub/gentoo/gentoo-distfiles/ \\
    rsync://ftp.rnl.tecnico.ulisboa.pt/pub/gentoo/gentoo-distfiles/ \\
    http://ftp.dei.uc.pt/pub/linux/gentoo/ \\
    https://repo.ifca.es/gentoo-distfiles \\
    rsync://repo.ifca.es/gentoo-distfiles \\
    ftp://repo.ifca.es/gentoo-distfiles"
