#!/bin/bash

# checks arguments, prints usage and prepares variables
[[ $# -gt 1 ]] && echo 'Usage: eclean [--unsupervised]' && exit 1
[[ $1 == '--unsupervised' ]] && UNSUPERVISED=$1

# defines flags checking functions
function is_unsupervised() { [[ ! -z ${UNSUPERVISED} ]] && return 0 || return 1; }

# defines permissions handling functions
function is_root() { [[ ${EUID} -eq 0 ]] && return 0 || return 1; }
function run_as_root() { if is_root; then ${@:2}; else ${@:1}; fi; }

# defines requirements checking functions
function check_command() { for CHECK_DEP in $@; do [[ -z $(command -v ${CHECK_DEP}) ]] && echo "Missing command: ${CHECK_DEP}" && exit 1; done; }

# defines portage functions
function clean_with_portage() { run_as_root doas emerge $1 --depclean; }

# checks required dependencies
check_command doas emerge
# removes deprecated artifacts from the system
is_unsupervised && clean_with_portage --ask=n || clean_with_portage --ask
