#!/usr/bin/nft -f
table inet filter {
  chain input {
    type filter hook input priority 0; policy drop;

    ct state invalid drop
    ip frag-off & 0x1fff != 0 drop
    iif != lo ip daddr 127.0.0.0/8 drop

    iif lo accept
    ct state established,related accept

    ip protocol icmp icmp type echo-request limit rate 4/second burst 8 packets accept
    ip protocol icmp icmp type { destination-unreachable,echo-reply,time-exceeded } accept

    tcp dport 22 ct state new limit rate 4/minute burst 8 packets accept
    tcp dport 443 ct state new limit rate 32/second burst 64 packets accept
  }

  chain forward { type filter hook forward priority 0; policy drop; }
  chain output { type filter hook output priority 0; policy accept; }
}
