#!/usr/bin/nft -f
table inet default {
  set banned { flags dynamic, timeout; timeout 10d; type ipv4_addr; }
  set trusted { flags dynamic, timeout; timeout 1d; type ipv4_addr; }

  chain forward { type filter hook forward priority filter; policy drop; }
  chain output { type filter hook output priority filter; policy accept; }

  chain prerouting {
    type nat hook prerouting priority dstnat
    policy accept

    tcp dport { 443 } redirect to 10443
  }

  chain input {
    type filter hook input priority filter
    policy drop

    ct state { established,related } accept
    iif lo accept

    ct state invalid drop
    iif != lo ip daddr 127.0.0.0/8 drop
    ip frag-off & 0x3fff != 0 drop
    ip saddr @banned drop

    ip saddr @trusted icmp type { echo-request } accept
    icmp type { destination-unreachable, echo-reply, time-exceeded } accept
    icmp type { echo-request } limit rate 16/second burst 16 packets accept
    icmp type { echo-request } add @banned { ip saddr } drop

    ip saddr @trusted tcp dport { 22 } ct state new accept
    tcp dport { 22 } ct state new limit rate 4/minute burst 4 packets accept
    tcp dport { 22 } ct state new add @banned { ip saddr } drop

    tcp dport { 10443 } ct status dnat limit rate 32/second burst 64 packets accept
  }
}

