agetty.ttyAMA0               # console
nftables                     # firewall
podman                       # socket
podman-compose.$_PODMAN_USER # containers start
sshd                         # ssh
