sys-kernel/gentoo-kernel-bin
sys-kernel/installkernel
sys-kernel/linux-firmware

app-admin/doas
app-admin/eclean-kernel
dev-vcs/git

net-firewall/nftables
net-misc/openssh
sys-process/fcron

app-containers/podman-compose
sys-process/htop

sys-process/btop
