#!/bin/bash

# dotfiles specific variables
export _HOST='bra-m0064'
export _USER='pereiped'
# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----

# dotfiles specific variables
_LAYERS=(
  "layers.d/base.d"
  "hosts.d/$_HOST.d"
)
# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
