# sets new prefix keys to ctrl + space
unbind c-b
set -g prefix ç
bind ç send-prefix

# enables mouse support and scroll back
set -g mouse on
set-option -g history-limit 50000



# bootstraps plugin manager
# set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.config/tmux/plugins/"
# if-shell -b "[[ ! -d ~/.config/tmux/plugins/tpm ]]" {
#   run-shell "git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins"
# }

# declares plugins
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'

set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -sg escape-time 5

# synchronizes plugins
# run-shell "~/.config/tmux/plugins/tpm/bin/install_plugins"
# run-shell "~/.config/tmux/plugins/tpm/bin/update_plugins all"
# run-shell "~/.config/tmux/plugins/tpm/bin/clean_plugins"
# initializes plugin manager 
# run-shell "~/.config/tmux/plugins/tpm/tpm"

# set-hook -g session-created 'send-keys "myvim" Enter'
#
# bind-key -T "prefixless" M-r "command-prompt 'rename-window %%'"

bind-key -n c-t new-window
