# https://gist.github.com/mzmonsour/8791835

set -ag terminal-overrides ",xterm-256color:RGB" # tmux color
set -g default-terminal "screen-256color" # tmux terminal type

set -g mouse on # mouse support
set-option -g history-limit 50000 # longer history

set -g renumber-windows on # index update on window close
set -g base-index 1 # index base 1
setw -g pane-base-index 1 # index base 1

set -sg escape-time 5 # vim escape press delay

set-hook -g session-created 'send-keys "tmux-muxinator" ENTER;' # template layout
set-option -g detach-on-destroy off # switches to next session when one closes

# manage tmux
bind-key -n m-R run-shell 'tmux source-file ~/.config/tmux/tmux.conf && tmux display-message "Reloaded"' # reload tmux configuration - alt + shift + r
bind-key -n m-space run-shell 'tmux choose-session' # load session - alt + space

# close sessions, windows and tabs
bind-key -n m-q run-shell 'tmux kill-pane' # close tab - alt + q
bind-key -n m-Q run-shell 'tmux kill-session' # close session - alt + shift + q

# create windows and tabs
bind-key -n m-Enter run-shell 'tmux new-window' # create window - alt + enter
bind-key -n m-t run-shell 'tmux split-window -h' # create tab - alt + t
bind-key -n m-T run-shell 'tmux split-window -v' # create horizontal tab - alt + shift + t

# navigate windows
bind-key -n m-Tab run-shell 'tmux last-window' # cycle to previous window - alt + tab
bind-key -n m-1 run-shell 'tmux select-window -t :1' # navigate to window 1 - alt + 1
bind-key -n m-2 run-shell 'tmux select-window -t :2' # navigate to window 2 - alt + 2
bind-key -n m-3 run-shell 'tmux select-window -t :3' # navigate to window 3 - alt + 3
bind-key -n m-4 run-shell 'tmux select-window -t :4' # navigate to window 4 - alt + 4
bind-key -n m-5 run-shell 'tmux select-window -t :5' # navigate to window 5 - alt + 5
bind-key -n m-6 run-shell 'tmux select-window -t :6' # navigate to window 6 - alt + 6
bind-key -n m-7 run-shell 'tmux select-window -t :7' # navigate to window 7 - alt + 7
bind-key -n m-8 run-shell 'tmux select-window -t :8' # navigate to window 8 - alt + 8
bind-key -n m-9 run-shell 'tmux select-window -t :9' # navigate to window 9 - alt + 9
bind-key -n m-0 run-shell 'tmux select-window -t :0' # navigate to window 0 - alt + 0

# navigate tabs
bind-key -n m-h run-shell 'tmux select-pane -L' # select left tab - alt + h
bind-key -n m-j run-shell 'tmux select-pane -D' # select down tab - alt + j
bind-key -n m-k run-shell 'tmux select-pane -U' # select up tab - alt + k
bind-key -n m-l run-shell 'tmux select-pane -R' # select right tab - alt + l
bind-key -n m-Left run-shell 'tmux select-pane -L' # select left tab - alt + left arrow
bind-key -n m-Down run-shell 'tmux select-pane -D' # select down tab - alt + down arrow
bind-key -n m-Up run-shell 'tmux select-pane -U' # select up tab - alt + up arrow
bind-key -n m-Right run-shell 'tmux select-pane -R' # select right tab - alt + right arrow

# resize tabs
bind-key -n m-H run-shell 'tmux resize-pane -L' # resize tab to left - alt + shift + h
bind-key -n m-J run-shell 'tmux resize-pane -D' # resize tab to down - alt + shift + j
bind-key -n m-K run-shell 'tmux resize-pane -U' # resize tab to up - alt + shift + k
bind-key -n m-L run-shell 'tmux resize-pane -R' # resize tab to right - alt + shift + l
