set -ag terminal-overrides ",xterm-256color:RGB" # tmux color
set -g base-index 1 # index base 1
set -g default-terminal "screen-256color" # tmux terminal type
set -g mouse on # mouse support
set -g renumber-windows on # index update on window close
set -sg escape-time 5 # vim escape press delay
set -sg repeat-time 2500 # tmux key sequence timeout
set-option -g history-limit 50000 # longer history
setw -g pane-base-index 1 # index base 1

# prefix key
unbind C-b
set -g prefix ç
bind ç send-prefix
# key mappings
bind-key r run-shell 'tmux source-file ~/.config/tmux/tmux.conf && tmux display-message "Reloaded"'
# manage sessions, windows and panes
bind-key n run-shell 'tmux new-window'
bind-key t run-shell 'tmux split-window -h'
bind-key T run-shell 'tmux split-window -v'
bind-key o run-shell 'tmux choose-session'
bind-key O run-shell 'tmux choose-window'
bind-key Q run-shell 'tmux kill-session'
bind-key q run-shell 'tmux kill-pane'
# navigate panes
bind-key -r h run-shell 'tmux select-pane -L'
bind-key -r j run-shell 'tmux select-pane -D'
bind-key -r k run-shell 'tmux select-pane -U'
bind-key -r l run-shell 'tmux select-pane -R'
bind-key -r Tab run-shell 'tmux last-window'

# post session created event
# set-hook -g session-created "send-keys 'tmux-muxinator' Enter"

# bootstraps plugin manager
# set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.config/tmux/plugins/"
# if-shell -b "[[ ! -d ~/.config/tmux/plugins/tpm ]]" {
#   run-shell "git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins"
# }

# declares plugins
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'

# synchronizes plugins
# run-shell "~/.config/tmux/plugins/tpm/bin/install_plugins"
# run-shell "~/.config/tmux/plugins/tpm/bin/update_plugins all"
# run-shell "~/.config/tmux/plugins/tpm/bin/clean_plugins"
# initializes plugin manager 
# run-shell "~/.config/tmux/plugins/tpm/tpm"
