macosSettings:
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.mouse.tapBehavior", "value": 1}
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.enableSecondaryClick", "value": true}
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.fiveFingerPinchSwipeGesture", "value": 0}
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.fourFingerHorizSwipeGesture", "value": 0}
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.fourFingerPinchSwipeGesture", "value": 0}
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.fourFingerVertSwipeGesture", "value": 0}
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.momentumScroll", "value": false}
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.pinchGesture", "value": false}
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.rotateGesture", "value": false}
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.scrollBehavior", "value": 2}
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.threeFingerDragGesture", "value": false}
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.threeFingerHorizSwipeGesture", "value": 0}
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.threeFingerTapGesture", "value": 0}
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.threeFingerVertSwipeGesture", "value": 0}
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.twoFingerDoubleTapGesture", "value": 0}
  - {"scope": "current-host", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.twoFingerFromRightEdgeSwipeGesture", "value": 0}
  - {"scope": "current-host", "domain": "com.apple.controlcenter", "key": "AirplayReceiverEnabled", "value": false}
  - {"scope": "current-host", "domain": "com.apple.controlcenter", "key": "BatteryShowPercentage", "value": true}
  - {"scope": "current-host", "domain": "com.apple.controlcenter", "key": "Display", "value": 8}
  - {"scope": "current-host", "domain": "com.apple.controlcenter", "key": "FocusModes", "value": 8}
  - {"scope": "current-host", "domain": "com.apple.controlcenter", "key": "NowPlaying", "value": 8}
  - {"scope": "current-host", "domain": "com.apple.controlcenter", "key": "ScreenMirroring", "value": 8}
  - {"scope": "current-host", "domain": "com.apple.controlcenter", "key": "Sound", "value": 8}
  - {"scope": "current-host", "domain": "com.apple.controlcenter", "key": "Spotlight", "value": 8}
  - {"scope": "current-host", "domain": "com.apple.controlcenter", "key": "Timer", "value": 8}
  - {"scope": "current-host", "domain": "com.apple.controlcenter", "key": "VoiceControl", "value": 8}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "AppleAccentColor", "value": 4}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "AppleActionOnDoubleClick", "value": "None"}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "AppleEnableSwipeNavigateWithScrolls", "value": false}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "AppleIconAppearanceTheme", "value": "RegularDark"}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "AppleInterfaceStyle", "value": "Dark"}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "AppleLanguages", "value": ["en-US", "pt-PT"]}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "AppleLocale", "value": "en_US@rg=ptzzzz"}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "AppleShowScrollBars", "value": "Always"}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "AppleSpacesSwitchOnActivate", "value": false}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "InitialKeyRepeat", "value": 15}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "KeyRepeat", "value": 2}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "NSAutomaticCapitalizationEnabled", "value": true}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "NSAutomaticPeriodSubstitutionEnabled", "value": true}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "NSTableViewDefaultSizeMode", "value": 2}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "com.apple.mouse.doubleClickThreshold", "value": 0.15}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "com.apple.mouse.scaling", "value": 1.0}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "com.apple.scrollwheel.scaling", "value": 1.7}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "com.apple.sound.beep.feedback", "value": false}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "com.apple.sound.beep.flash", "value": false}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "com.apple.sound.uiaudio.enabled", "value": false}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "com.apple.springing.delay", "value": 0.5}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "com.apple.springing.enabled", "value": false}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "com.apple.swipescrolldirection", "value": false}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.forceClick", "value": false}
  - {"scope": "defaults", "domain": "NSGlobalDomain", "key": "com.apple.trackpad.scrolling", "value": true}
  - {"scope": "defaults", "domain": "com.apple.Accessibility", "key": "DifferentiateWithoutColor", "value": true}
  - {"scope": "defaults", "domain": "com.apple.Accessibility", "key": "ReduceMotionEnabled", "value": true}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchMouse", "key": "MouseButtonDivision", "value": 55}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchMouse", "key": "MouseButtonMode", "value": "OneButton"}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchMouse", "key": "MouseOneFingerDoubleTapGesture", "value": 0}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchMouse", "key": "MouseTwoFingerDoubleTapGesture", "value": 3}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchMouse", "key": "MouseTwoFingerHorizSwipeGesture", "value": 2}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "ActuateDetents", "value": false}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "Clicking", "value": true}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "DragLock", "value": false}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "Dragging", "value": false}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "ForceSuppressed", "value": true}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "TrackpadFiveFingerPinchGesture", "value": 0}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "TrackpadFourFingerHorizSwipeGesture", "value": 0}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "TrackpadFourFingerPinchGesture", "value": 0}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "TrackpadFourFingerVertSwipeGesture", "value": 0}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "TrackpadMomentumScroll", "value": false}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "TrackpadPinch", "value": false}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "TrackpadRightClick", "value": true}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "TrackpadRotate", "value": false}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "TrackpadThreeFingerDrag", "value": false}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "TrackpadThreeFingerHorizSwipeGesture", "value": 0}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "TrackpadThreeFingerTapGesture", "value": 0}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "TrackpadThreeFingerVertSwipeGesture", "value": 0}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "TrackpadTwoFingerDoubleTapGesture", "value": 0}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "TrackpadTwoFingerFromRightEdgeSwipeGesture", "value": 0}
  - {"scope": "defaults", "domain": "com.apple.AppleMultitouchTrackpad", "key": "USBMouseStopsTrackpad", "value": true}
  - {"scope": "defaults", "domain": "com.apple.HIToolbox", "key": "AppleCurrentKeyboardLayoutInputSourceID", "value": "com.apple.keylayout.Portuguese"}
  - {"scope": "defaults", "domain": "com.apple.HIToolbox", "key": "AppleFnUsageType", "value": 0}
  - {"scope": "defaults", "domain": "com.apple.WindowManager", "key": "AppWindowGroupingBehavior", "value": 0}
  - {"scope": "defaults", "domain": "com.apple.WindowManager", "key": "AutoHide", "value": true}
  - {"scope": "defaults", "domain": "com.apple.WindowManager", "key": "EnableStandardClickToShowDesktop", "value": false}
  - {"scope": "defaults", "domain": "com.apple.WindowManager", "key": "EnableTiledWindowMargins", "value": false}
  - {"scope": "defaults", "domain": "com.apple.WindowManager", "key": "EnableTilingByEdgeDrag", "value": false}
  - {"scope": "defaults", "domain": "com.apple.WindowManager", "key": "EnableTilingOptionAccelerator", "value": false}
  - {"scope": "defaults", "domain": "com.apple.WindowManager", "key": "EnableTopTilingByEdgeDrag", "value": false}
  - {"scope": "defaults", "domain": "com.apple.WindowManager", "key": "HideDesktop", "value": true}
  - {"scope": "defaults", "domain": "com.apple.WindowManager", "key": "StageManagerHideWidgets", "value": true}
  - {"scope": "defaults", "domain": "com.apple.WindowManager", "key": "StandardHideWidgets", "value": true}
  - {"scope": "defaults", "domain": "com.apple.controlcenter", "key": "NSStatusItem VisibleCC Battery", "value": true}
  - {"scope": "defaults", "domain": "com.apple.controlcenter", "key": "NSStatusItem VisibleCC BentoBox-0", "value": true}
  - {"scope": "defaults", "domain": "com.apple.controlcenter", "key": "NSStatusItem VisibleCC Clock", "value": true}
  - {"scope": "defaults", "domain": "com.apple.controlcenter", "key": "NSStatusItem VisibleCC NowPlaying", "value": true}
  - {"scope": "defaults", "domain": "com.apple.controlcenter", "key": "NSStatusItem VisibleCC WiFi", "value": true}
  - {"scope": "defaults", "domain": "com.apple.controlcenter", "key": "RemoteLiveActivitiesEnabled", "value": false}
  - {"scope": "defaults", "domain": "com.apple.dock", "key": "autohide", "value": false}
  - {"scope": "defaults", "domain": "com.apple.dock", "key": "enterMissionControlByTopWindowDrag", "value": false}
  - {"scope": "defaults", "domain": "com.apple.dock", "key": "largesize", "value": 16}
  - {"scope": "defaults", "domain": "com.apple.dock", "key": "launchanim", "value": false}
  - {"scope": "defaults", "domain": "com.apple.dock", "key": "magnification", "value": false}
  - {"scope": "defaults", "domain": "com.apple.dock", "key": "mru-spaces", "value": false}
  - {"scope": "defaults", "domain": "com.apple.dock", "key": "show-process-indicators", "value": false}
  - {"scope": "defaults", "domain": "com.apple.dock", "key": "show-recents", "value": false}
  - {"scope": "defaults", "domain": "com.apple.dock", "key": "showDesktopGestureEnabled", "value": false}
  - {"scope": "defaults", "domain": "com.apple.dock", "key": "showMissionControlGestureEnabled", "value": false}
  - {"scope": "defaults", "domain": "com.apple.dock", "key": "tilesize", "value": 32}
  - {"scope": "defaults", "domain": "com.apple.dock", "key": "wvous-br-corner", "value": 1}
  - {"scope": "defaults", "domain": "com.apple.dock", "key": "wvous-br-modifier", "value": 0}
  - {"scope": "defaults", "domain": "com.apple.finder", "key": "FXArrangeGroupViewBy", "value": "Name"}
  - {"scope": "defaults", "domain": "com.apple.finder", "key": "FXICloudDriveDesktop", "value": false}
  - {"scope": "defaults", "domain": "com.apple.finder", "key": "FXICloudDriveDocuments", "value": false}
  - {"scope": "defaults", "domain": "com.apple.finder", "key": "NewWindowTarget", "value": "PfHm"}
  - {"scope": "defaults", "domain": "com.apple.finder", "key": "ShowExternalHardDrivesOnDesktop", "value": true}
  - {"scope": "defaults", "domain": "com.apple.finder", "key": "ShowHardDrivesOnDesktop", "value": false}
  - {"scope": "defaults", "domain": "com.apple.finder", "key": "ShowMountedServersOnDesktop", "value": true}
  - {"scope": "defaults", "domain": "com.apple.finder", "key": "ShowPathbar", "value": true}
  - {"scope": "defaults", "domain": "com.apple.finder", "key": "ShowPreviewPane", "value": false}
  - {"scope": "defaults", "domain": "com.apple.finder", "key": "ShowRemovableMediaOnDesktop", "value": true}
  - {"scope": "defaults", "domain": "com.apple.finder", "key": "ShowStatusBar", "value": true}
  - {"scope": "defaults", "domain": "com.apple.loginwindow", "key": "TALLogoutSavesState", "value": false}
  - {"scope": "defaults", "domain": "com.apple.menuextra.clock", "key": "ShowAMPM", "value": true}
  - {"scope": "defaults", "domain": "com.apple.menuextra.clock", "key": "ShowDate", "value": 0}
  - {"scope": "defaults", "domain": "com.apple.menuextra.clock", "key": "ShowDayOfWeek", "value": true}
  - {"scope": "defaults", "domain": "com.apple.spaces", "key": "spans-displays", "value": false}
