#!/bin/bash

tmux send 'clear' ENTER;
tmux rename-window 'nvim'
tmux send 'nvim-hot-reloadable' ENTER;

tmux new-window -n 'terminal'

tmux new-window -n 'git'
tmux send 'lazygit' ENTER;

tmux select-window -t :1
