#!/bin/bash
set -eo pipefail

[[ ${EUID} -ne 0 ]] && su root -c "$0" "$@" && exit $?

dracut --force --hostonly --kver "$(eselect kernel list | grep --only-matching --perl-regexp 'linux-\K[^ ]+')" --quiet
grub-mkconfig --output=/boot/grub/grub.cfg
